---
  output: github_document
  always_allow_html: true
---

  <!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R packages for AMNOG analyses

Ramnog is a collection of packages for setting up pipelines for AMNOG-style HTA analyses

The aim of ramnog is that statistician/programmer can set up an AMNOG-type analyses with minimal familiarity with R.

# Packages
 
```{r, echo=FALSE}
library(kableExtra)
library(data.table)
dt <-  data.table::data.table(
  Package = c( "chef", "chefStats", "chefCriteria","ramnog"),
    Description = c(
      "Core package that aids in creating endpoint specifications, builds the analysis pipeline, and coordinates the execution of the ananlyses",
      "Collection of statistical methods that are used to make summarizations or inferences for each endpoint/outcome",
      "Collection of criteria that are used in AMNOG dossiers to determin when specific analyses/statistics should be calculated",
      "Wrapper package tying ecosystem together"
    )
)
  
  dt |> 
  kable(format = "html", table.attr = "class='table table-bordered'") |> 
  kable_styling(bootstrap_options = c("hover", "condensed", "responsive")) |> 
  row_spec(0, background = "lightblue")
  
```
