---
title: "Contributing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Contributing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```




# Definition of done

A feature branch is defined as done and ready for a PR (pull request) into main branch only once it has been properly tested. Testing consists of:

1. Unit-tests to test the basic functionality 
2. Integration testing to ensure all features work together
3. Passing the CI/CD

Unit-testing and ingegration testing are done using the [testthat]() framework. New features usually, but no always require new tests.

If you are developing, for example a new statistical function for {chefStats} then it must be checked with unit tests.

Additionally, all previous unit-tests and integration tests need to pass. You can check this by running `devtools::test()` in the respective packages.

__Note:__ Integration testing mostly resides in {ramnog}, so you will need to run `devtools::test()` there as well.
